export const productsBaseDetails = {
    "packageFee": 120,
    "deliveryFee": 0,
    "itemsBasicDetails": [
      {
        "pkItemId": 1,
        "id": 1,
        "uniqueId": "mural_1",
        "itemName": "Mural && Blue",
        "rating": 4,
        "itemCartCount": 0,
        "reviewCount": 30,
        "itemDetail1": "100% chemical free",
        "itemDetail2": "Light Weigth",
        "itemDetail3": "Best finish",
        "itemDetail4": "Unique design",
        "itemDetail5": "For Men",
        "itemDetail6": "Casual",
        "description": "This is a best Perfume with full fragrance and deligence.",
        "discountPrice": 88,
        "actualPrice": 100,
        "imageName": "hlf_1.png                                         ",
        "orderItems": []
      },
      {
        "pkItemId": 2,
        "id": 2,
        "uniqueId": "powder_1",
        "itemName": "Powder Ittar",
        "rating": 3,
        "itemCartCount": 0,
        "reviewCount": 30,
        "itemDetail1": "100% chemical free",
        "itemDetail2": "Light Weigth",
        "itemDetail3": "Best finish",
        "itemDetail4": "Unique design",
        "itemDetail5": "For Men",
        "itemDetail6": "Casual",
        "description": "This is a best Perfume with full fragrance and deligence.",
        "discountPrice": 75,
        "actualPrice": 100,
        "imageName": "23.jpg                                            ",
        "orderItems": []
      },
      {
        "pkItemId": 3,
        "id": 3,
        "uniqueId": "phool_1",
        "itemName": "Phool Ittar",
        "rating": 3,
        "itemCartCount": 0,
        "reviewCount": 30,
        "itemDetail1": "100% chemical free",
        "itemDetail2": "Light Weigth",
        "itemDetail3": "Best finish",
        "itemDetail4": "Unique design",
        "itemDetail5": "For Men",
        "itemDetail6": "Casual",
        "description": "This is a best Perfume with full fragrance and deligence.",
        "discountPrice": 100,
        "actualPrice": 100,
        "imageName": "24.jpg                                            ",
        "orderItems": []
      }
    ]
  }